### PR TITLE
Added two more icons to AppbarIcons

### PR DESCRIPTION
**Pull request by cthedot**
I've added the already in the Symbol font present icons for "print" and "share" (the share icon from e.g. Edge"). At least "share" is available in https://msdn.microsoft.com/en-us/library/windows/apps/hh770557.aspx and should be present in WinJS based apps too. 
I use both in my own app and they seem to work. I added both to all language files (which is tidious and strange to have the same icon defs in so many files but guess there is a good reason?).

Any feedback welcome.

### CODE REVIEW

**Comment by jdalton** [comment]
@AmazingJaze Any objections?

**Comment by AmazingJaze** [comment]
My concern around taking this is if these icons are exclusive to the new font family.  
I think bug #1252 is tracking the work to update the AppBarIcons enumeration to all the new fonts and symbols.  

If these same icons are part of that work, I think it would be better to update them all at once, rather than making piecemeal updates. Additionally, until we have a new web font ready, any changes we make will not work cross platform.

**Comment by cthedot** [comment]
@AmazingJaze your comment is a bit surprising and almost disturbing. I ran into the missing share icon while building a Windows 10 app and was looking at the docs https://msdn.microsoft.com/en-us/library/windows/apps/hh770557.aspx?f=255&MSPPError=-2147217396 . These include the share icon which is also prominently used in e.g. Edge. I consider the missing icon in WInJS a bug. 
(I also added the print icon as IMHO this is an icon which would be used quite often in apps/webapps too.)

I understand your concerns about cross platform. But WinJS originates from WinJS Windows 8/8.1/10 development so at least should include all that is described there? 
Generally it is great to have WinJS available to be used outside Windows App dev but it is not so nice that there is no complete documentation anymore what is included where. Docs at MSDN claim stuff like the Share icon that is not in WinJS, OTOH omit stuff that is in newer WInjS (like ListView header/footer) so it is actually harder to build something with WinJS now than it was on Windows 8 or 8.1 :(

This seems a general problem and I am not sure if this is the place to discuss it but I like WinJS and like to use it with all the latest features and bugfixes in my app but currently this is very hard. And even if I who may not be one of the better nor brightest devs but guess one of the devs who use WinJS for quite a long time already (>3 years) has a hard time why should anyone use WinJS for apps even outside Windows App dev?

Sorry about the rant but I maybe naively assumed added one or two icons would be quite easy. I currently have to patch any new WinJS version I add with the icons which is less than an ideal situation.

**Comment by AmazingJaze** [comment]
Hi @cthedot, I don't disagree that updating these icons is an important addition to WinJS. I think I ended my previous comment short of one important sentence which is that I'll defer to @jdalton and @jayrenn  on whether or not we want to take this change ahead of the work @jayrenn was tracking for  #1252.

Aside from that, re-reviewing the contents of the change, I noticed that you are updating all of the previous versioned winjs.d.ts files (1.0, 2.0, 2.1, 3.0) in your second commit. However, those files should not be changed as they correspond to past releases of WinJS that will not include these icons. 

If you can revert those d.ts files and only include the change in typings/winjs/winjs.d.ts file, then I see no issues as far as overall correctness is concerned.

**Comment by cthedot** [comment]
thanks, I was a bit ranty this morning I guess ;) Also saw that #1252 was closed. Your additional comment make sense now and I hope the work (and docs) will improve now.

Guess I made myself too much work by changing all files, was wondering what they are anyway. I see what I can do (just published my app to the store so am still a bit busy ;).
Thanks!

**Comment by AmazingJaze** [comment]
Thanks, and just to be clear, Most of the 100+ files do need the change. It's just the 4 versioned WinJS.d.ts files (1.0, 2.0, 2.1 and 3.0) that we don't want to change here.

**Comment by cthedot** [comment]
I feared so. I think I did change all language versions. BTW, is there any way to improve this? Any icon change would need to do this but (at least to my naive view) all icons are the same for all languages anyway, and even if not is there no way to "overwrite" them in specific files or so? I guess I can only fix my PR next week, as am too busy this weekend and away for 2 days as well.

**Comment by cthedot** [comment]
I created a new pull request #1515 which replaces this one (no more changes in legacy WinJS.d.ts files. Please simply close this PR and I hope new one is better now.

**Pull request closed without merging**
